name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bd57dee05d8c444e55fe63da5c25a5ec2623a47e1bbe93accc866652f1e50ee"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
