name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7bd611ad3e4e0f2b04343e35564e27e8ba57db6ca58e27007190af44a4e7f8"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
